<template>
    <div class="loading-container">
        <div class="loader">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="200"
                height="200" style="shape-rendering: auto; display: block; background: rgb(255, 255, 255);"
                xmlns:xlink="http://www.w3.org/1999/xlink">
                <g>
                    <circle stroke-dasharray="164.93361431346415 56.97787143782138" r="35" stroke-width="10"
                        stroke="#9a0052" fill="none" cy="50" cx="50">
                        <animateTransform keyTimes="0;1" values="0 50 50;360 50 50" dur="1s" repeatCount="indefinite"
                            type="rotate" attributeName="transform"></animateTransform>
                    </circle>
                    <g></g>
                </g><!-- [ldio] generated by https://loading.io -->
            </svg>
        </div>
        <div class="loading-text"> 
            {{label}}
        </div>
    </div>
</template>

<script setup>

const props = defineProps({
  label: {
    type: String,
    default: 'Chargement...'
  },
})

</script>

<style scoped>
.loading-container {
    display: flex;
    flex-direction: column;
    justify-content: center; /* Centrer verticalement */
    align-items: center; /* Centrer horizontalement */
    height: 50vh; /* S'assurer qu'il occupe toute la hauteur disponible */
    width: 100%; /* S'assurer qu'il occupe toute la largeur */
}

.loader {
    margin: 0 auto;
    display: block;
}

.loading-text {
    margin-top: 1rem;
    font-size: 1.5rem;
    font-weight: bold;
    color: var(--primary-color);
}
</style>
